// Automatically generated by modcc

#include <arbor/mechanism_abi.h>

#include "read.hpp"

#ifdef STANDALONE
extern "C" {
    [[gnu::visibility("default")]] const void* get_catalogue(int* n) {
        *n = 1;
        static arb_mechanism cat[1] = {
            make_arb_the_catalogue_read(),
        };
        return (void*)cat;
    }
}

#else

#include <arbor/mechanism.hpp>
#include <arbor/assert.hpp>

#include "the_catalogue.hpp"

namespace arb {
mechanism_catalogue build_the_catalogue() {
    mechanism_catalogue cat;
    {
        auto mech = make_arb_the_catalogue_read();
        auto ty = mech.type();
        auto nm = ty.name;
        auto ig = mech.i_gpu();
        auto ic = mech.i_cpu();
        arb_assert(ic || ig);
        cat.add(nm, ty);
        if (ic) cat.register_implementation(nm, std::make_unique<arb::mechanism>(ty, *ic));
        if (ig) cat.register_implementation(nm, std::make_unique<arb::mechanism>(ty, *ig));
    }
    return cat;
}

ARB_ARBOR_API const mechanism_catalogue& global_the_catalogue() {
    static mechanism_catalogue cat = build_the_catalogue();
    return cat;
}
} // namespace arb
#endif
